---
  - name: Test - Set AptCacher Proxy
    hosts: test
    become: true
    tasks:
      - name: Test - Set AptCacher Proxy
        copy:
          src: /home/jeremy/ansible/99AptCacher
          dest: /etc/apt/apt.conf.d/99AptCacher
          owner: root
          group: root
          mode: '0644'
