---
  - name: Test - Set AptCacher Proxy
    hosts: test
    become: yes
    tasks:
      - name: Test - Set AptCacher Proxy
        copy:
          src: /etc/ansible/files/99AptCacher
          dest: /etc/apt/apt.conf.d/99AptCacher
          owner: root
          group: root
          mode: '0644'
