---
  - name: Test - Set AptCacher Proxy
    hosts: test
    become: true
    remote_user: jeremy
    become_method: sudo
    tasks:
      - name: Test - Set AptCacher Proxy
        copy:
          src: /etc/ansible/files/99AptCacher
          dest: /etc/apt/apt.conf.d/99AptCacher
